/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare enum OcrAccuracy {
  Fast = 0,
  Accurate = 1
}

export interface OcrResult {
  text: string
  /**
   * Always 1.0 on Windows. On macOS 26+, also 1.0 when the
   * `RecognizeDocumentsRequest` (structured-document) path is used — that
   * API does not surface per-observation confidence. Callers that need the
   * averaged `VNRecognizeTextRequest` confidence should pass an explicit
   * `accuracy` of `Fast` or a non-empty `preferredLangs`, which routes the
   * request through the legacy text-recognition path.
   */
  confidence: number
}

/**
 * @param image - The image file path or Buffer
 * @param accuracy - The accuracy of the OCR. Default is `Accurate`. Ignored on Windows.
 * @param preferredLangs - The preferred languages for the OCR. Default is `["en-US"]`. On Windows, only the first language is used.
 * @param signal - The signal to abort the OCR.
 */
export declare function recognize(image: string | Uint8Array, accuracy?: OcrAccuracy | undefined | null, preferredLangs?: Array<string> | undefined | null, signal?: AbortSignal | undefined | null): Promise<OcrResult>
