/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum OcrAccuracy {
  Fast = 0,
  Accurate = 1
}

export interface OcrResult {
  text: string
  confidence: number
}

export declare function recognize(image: string | Uint8Array, accuracy: OcrAccuracy, preferedLangs?: Array<string> | undefined | null, signal?: AbortSignal | undefined | null): Promise<OcrResult>
